apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-starwars-api
  namespace: {{ .Values.namespace }}
  labels:
    app: node-starwars-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-starwars-api
  template:
    metadata:
      labels:
        app: node-starwars-api
    spec:
      containers:
      - name: node-starwars-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
