replicaCount: 3

namespace: fastapi-starwars-api

image:
  repository: bmo75/fastapi-starwars-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5002
  nodePort: 30005

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
